In [1]:
from financial_dataset_preprocessor import *

INFO:shining_pebbles:shining_pebbles package initialized

In [4]:
ts = get_timeseries_fund_price(fund_code='100004')
ts

26 Files matching the regex 'menu2160-code100004' in the bucket 'dataset-system' with prefix 'dataset-menu2160/':
Successfully read file: dataset-menu2160/menu2160-code100004-from20200101-to20250216-save20250217.csv
DataFrame shape: (1300, 23)

              price
date
2021-07-28  1000.00
2021-07-29  1000.01
2021-07-30  1000.02
2021-07-31  1000.02
2021-08-01  1000.03
...             ...
2025-02-12  1749.73
2025-02-13  1757.84
2025-02-14  1776.61
2025-02-15  1776.64
2025-02-16  1776.66

[1300 rows x 1 columns]

In [2]:
df = get_preprocessed_menu2160(fund_code='100004')
df

26 Files matching the regex 'menu2160-code100004' in the bucket 'dataset-system' with prefix 'dataset-menu2160/':
Successfully read file: dataset-menu2160/menu2160-code100004-from20200101-to20250216-save20250217.csv
DataFrame shape: (1300, 23)

,펀드명,펀드,기준가,기준가: 증감,과표기준가,과표기준가: 증감,수정기준가,수정기준가: 증감,KOSPI,수익률: 펀드,...,설정잔액,편입비중: 주식,편입비중: 채권,편입비중: 파생,편입비중: 단기,펀드듀레이션,결산여부,결산후기준가,결산후기준가: 증감,통화
일자,,,,,,,,,,,,,,,,,,,,,
2021-07-29,라이프한국기업ESG향상일반사모투자신탁제1호,100004,1000.01,0.01,1000.01,0.01,1000.01,0.01,3242.65,0,...,3.050000e+10,0,0,0,100.00,0.0,NaN,NaN,0.0,NaN
2021-07-30,라이프한국기업ESG향상일반사모투자신탁제1호,100004,1000.02,0.01,1000.01,0.00,1000.02,0.01,3202.32,0,...,3.050000e+10,0.23,0,0,100.00,0.0,NaN,NaN,0.0,NaN
2021-07-31,라이프한국기업ESG향상일반사모투자신탁제1호,100004,1000.02,0.00,1000.02,0.01,1000.02,0.00,3202.32,0,...,3.050000e+10,0.23,0,0,100.00,0.0,NaN,NaN,0.0,NaN
2021-08-01,라이프한국기업ESG향상일반사모투자신탁제1호,100004,1000.03,0.01,1000.03,0.01,1000.03,0.01,3202.32,0,...,3.050000e+10,0.23,0,0,100.00,0.0,NaN,NaN,0.0,NaN
2021-08-02,라이프한국기업ESG향상일반사모투자신탁제1호,100004,1000.01,-0.02,1000.03,0.00,1000.01,-0.02,3223.04,0,...,3.050000e+10,1.55,0,0,100.00,0.0,NaN,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-02-12,라이프한국기업ESG향상일반사모투자신탁제1호,100004,1072.14,0.35,1000.85,0.01,1749.73,0.57,2548.39,0.03,...,1.500775e+11,82.63,0,0,17.48,0.0,NaN,NaN,0.0,NaN
2025-02-13,라이프한국기업ESG향상일반사모투자신탁제1호,100004,1077.11,4.97,1000.79,-0.06,1757.84,8.11,2583.17,0.46,...,1.500775e+11,82.80,0,0,17.22,0.0,NaN,NaN,0.0,NaN
2025-02-14,라이프한국기업ESG향상일반사모투자신탁제1호,100004,1088.61,11.50,1000.81,0.02,1776.61,18.77,2591.05,1.07,...,1.500775e+11,83.52,0,0,17.04,0.0,NaN,NaN,0.0,NaN
2025-02-15,라이프한국기업ESG향상일반사모투자신탁제1호,100004,1088.63,0.02,1000.82,0.01,1776.64,0.03,2591.05,0,...,1.500775e+11,83.52,0,0,17.04,0.0,NaN,NaN,0.0,NaN
2025-02-16,라이프한국기업ESG향상일반사모투자신탁제1호,100004,1088.64,0.01,1000.84,0.02,1776.66,0.02,2591.05,0,...,1.500775e+11,83.52,0,0,17.04,0.0,NaN,NaN,0.0,NaN

In [11]:
COLUMN_NAME_FOR_TIMESERIES_MENU2160 = '수정기준가'
COMLUMN_NAME_FOR_ADJUSTED_PRICE = 'price'
INDEX_NAME_FOR_DATE = 'date'

In [13]:
df = get_preprocessed_menu2160(fund_code='100004')
df = df[[COLUMN_NAME_FOR_TIMESERIES_MENU2160]].rename(columns={COLUMN_NAME_FOR_TIMESERIES_MENU2160: COMLUMN_NAME_FOR_ADJUSTED_PRICE})
df.index.name = INDEX_NAME_FOR_DATE
df

26 Files matching the regex 'menu2160-code100004' in the bucket 'dataset-system' with prefix 'dataset-menu2160/':
Successfully read file: dataset-menu2160/menu2160-code100004-from20200101-to20250216-save20250217.csv
DataFrame shape: (1300, 23)

              price
date
2021-07-29  1000.01
2021-07-30  1000.02
2021-07-31  1000.02
2021-08-01  1000.03
2021-08-02  1000.01
...             ...
2025-02-12  1749.73
2025-02-13  1757.84
2025-02-14  1776.61
2025-02-15  1776.64
2025-02-16  1776.66

[1299 rows x 1 columns]

In [14]:
def inject_zeroth_row_price_in_timeseries_menu2160(df, price_zeroth_row=INITIAL_PRICE_DEFAULT):
    dates = df.index.dropna()
    date_first = dates[0]
    date_zeroth = get_date_n_days_ago(date_first, 1)
    df.loc[date_zeroth, df.columns[0]] = price_zeroth_row
    df = df.sort_index(ascending=True)
    return df

In [15]:
preprocess_zeroth_row_price_in_timeseries_menu2160(df)

              price
date
2021-07-28  1000.00
2021-07-29  1000.01
2021-07-30  1000.02
2021-07-31  1000.02
2021-08-01  1000.03
...             ...
2025-02-12  1749.73
2025-02-13  1757.84
2025-02-14  1776.61
2025-02-15  1776.64
2025-02-16  1776.66

[1300 rows x 1 columns]

In [4]:
raw = load_menu2160(fund_code='100004')
raw

26 Files matching the regex 'menu2160-code100004' in the bucket 'dataset-system' with prefix 'dataset-menu2160/':
Successfully read file: dataset-menu2160/menu2160-code100004-from20200101-to20250216-save20250217.csv
DataFrame shape: (1300, 23)

,펀드명,펀드,기준가,증감,과표\n기준가,증감.1,수정\n기준가,증감.2,KOSPI,수익률,...,설정잔액,편입비중,Unnamed: 16,Unnamed: 17,Unnamed: 18,펀드\n듀레이션,결산\n여부,결산후\n기준가,증감.3,통화
일자,,,,,,,,,,,,,,,,,,,,,
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,펀드,...,NaN,주식,채권,파생,단기,NaN,NaN,NaN,NaN,NaN
2021-07-29,라이프한국기업ESG향상일반사모투자신탁제1호,100004.0,"1,000.01",0.01,"1,000.01",0.01,"1,000.01",0.01,"3,242.65",0,...,"30,500,000,000.00",0,0,0,100.00,0.0,NaN,NaN,0.0,NaN
2021-07-30,라이프한국기업ESG향상일반사모투자신탁제1호,100004.0,"1,000.02",0.01,"1,000.01",0.00,"1,000.02",0.01,"3,202.32",0,...,"30,500,000,000.00",0.23,0,0,100.00,0.0,NaN,NaN,0.0,NaN
2021-07-31,라이프한국기업ESG향상일반사모투자신탁제1호,100004.0,"1,000.02",0.00,"1,000.02",0.01,"1,000.02",0.00,"3,202.32",0,...,"30,500,000,000.00",0.23,0,0,100.00,0.0,NaN,NaN,0.0,NaN
2021-08-01,라이프한국기업ESG향상일반사모투자신탁제1호,100004.0,"1,000.03",0.01,"1,000.03",0.01,"1,000.03",0.01,"3,202.32",0,...,"30,500,000,000.00",0.23,0,0,100.00,0.0,NaN,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-02-12,라이프한국기업ESG향상일반사모투자신탁제1호,100004.0,"1,072.14",0.35,"1,000.85",0.01,"1,749.73",0.57,"2,548.39",0.03,...,"150,077,517,794.00",82.63,0,0,17.48,0.0,NaN,NaN,0.0,NaN
2025-02-13,라이프한국기업ESG향상일반사모투자신탁제1호,100004.0,"1,077.11",4.97,"1,000.79",-0.06,"1,757.84",8.11,"2,583.17",0.46,...,"150,077,517,794.00",82.80,0,0,17.22,0.0,NaN,NaN,0.0,NaN
2025-02-14,라이프한국기업ESG향상일반사모투자신탁제1호,100004.0,"1,088.61",11.50,"1,000.81",0.02,"1,776.61",18.77,"2,591.05",1.07,...,"150,077,517,794.00",83.52,0,0,17.04,0.0,NaN,NaN,0.0,NaN
2025-02-15,라이프한국기업ESG향상일반사모투자신탁제1호,100004.0,"1,088.63",0.02,"1,000.82",0.01,"1,776.64",0.03,"2,591.05",0,...,"150,077,517,794.00",83.52,0,0,17.04,0.0,NaN,NaN,0.0,NaN
2025-02-16,라이프한국기업ESG향상일반사모투자신탁제1호,100004.0,"1,088.64",0.01,"1,000.84",0.02,"1,776.66",0.02,"2,591.05",0,...,"150,077,517,794.00",83.52,0,0,17.04,0.0,NaN,NaN,0.0,NaN

In [4]:
df = preprocess_raw_menu2160(raw)
df

,펀드명,펀드,기준가,기준가: 증감,과표기준가,과표기준가: 증감,수정기준가,수정기준가: 증감,KOSPI,수익률: 펀드,...,설정잔액,편입비중: 주식,편입비중: 채권,편입비중: 파생,편입비중: 단기,펀드듀레이션,결산여부,결산후기준가,결산후기준가: 증감,통화
일자,,,,,,,,,,,,,,,,,,,,,
2021-07-29,라이프한국기업ESG향상일반사모투자신탁제1호,100004,1000.01,0.01,1000.01,0.01,1000.01,0.01,3242.65,0,...,3.050000e+10,0,0,0,100.00,0.0,NaN,NaN,0.0,NaN
2021-07-30,라이프한국기업ESG향상일반사모투자신탁제1호,100004,1000.02,0.01,1000.01,0.00,1000.02,0.01,3202.32,0,...,3.050000e+10,0.23,0,0,100.00,0.0,NaN,NaN,0.0,NaN
2021-07-31,라이프한국기업ESG향상일반사모투자신탁제1호,100004,1000.02,0.00,1000.02,0.01,1000.02,0.00,3202.32,0,...,3.050000e+10,0.23,0,0,100.00,0.0,NaN,NaN,0.0,NaN
2021-08-01,라이프한국기업ESG향상일반사모투자신탁제1호,100004,1000.03,0.01,1000.03,0.01,1000.03,0.01,3202.32,0,...,3.050000e+10,0.23,0,0,100.00,0.0,NaN,NaN,0.0,NaN
2021-08-02,라이프한국기업ESG향상일반사모투자신탁제1호,100004,1000.01,-0.02,1000.03,0.00,1000.01,-0.02,3223.04,0,...,3.050000e+10,1.55,0,0,100.00,0.0,NaN,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-02-12,라이프한국기업ESG향상일반사모투자신탁제1호,100004,1072.14,0.35,1000.85,0.01,1749.73,0.57,2548.39,0.03,...,1.500775e+11,82.63,0,0,17.48,0.0,NaN,NaN,0.0,NaN
2025-02-13,라이프한국기업ESG향상일반사모투자신탁제1호,100004,1077.11,4.97,1000.79,-0.06,1757.84,8.11,2583.17,0.46,...,1.500775e+11,82.80,0,0,17.22,0.0,NaN,NaN,0.0,NaN
2025-02-14,라이프한국기업ESG향상일반사모투자신탁제1호,100004,1088.61,11.50,1000.81,0.02,1776.61,18.77,2591.05,1.07,...,1.500775e+11,83.52,0,0,17.04,0.0,NaN,NaN,0.0,NaN
2025-02-15,라이프한국기업ESG향상일반사모투자신탁제1호,100004,1088.63,0.02,1000.82,0.01,1776.64,0.03,2591.05,0,...,1.500775e+11,83.52,0,0,17.04,0.0,NaN,NaN,0.0,NaN
2025-02-16,라이프한국기업ESG향상일반사모투자신탁제1호,100004,1088.64,0.01,1000.84,0.02,1776.66,0.02,2591.05,0,...,1.500775e+11,83.52,0,0,17.04,0.0,NaN,NaN,0.0,NaN

In [9]:
COLUMN_NAME_PREPROCESSED_FOR_TIMESERIES = '수정기준가'
df[['수정기준가']]

              수정기준가
일자
2021-07-29  1000.01
2021-07-30  1000.02
2021-07-31  1000.02
2021-08-01  1000.03
2021-08-02  1000.01
...             ...
2025-02-12  1749.73
2025-02-13  1757.84
2025-02-14  1776.61
2025-02-15  1776.64
2025-02-16  1776.66

[1299 rows x 1 columns]

In [5]:
df.iloc[0]

펀드명           라이프한국기업ESG향상일반사모투자신탁제1호
펀드                             100004
기준가                           1000.01
기준가: 증감                          0.01
과표기준가                         1000.01
과표기준가: 증감                        0.01
수정기준가                         1000.01
수정기준가: 증감                        0.01
KOSPI                         3242.65
수익률: 펀드                            0
수익률: KOSPI                       0.18
수익률: 초과                         -0.18
순자산총액                   30500192191.0
설정잔액                    30500000000.0
편입비중: 주식                           0
편입비중: 채권                           0
편입비중: 파생                           0
편입비중: 단기                       100.00
펀드듀레이션                            0.0
결산여부                              NaN
결산후기준가                            NaN
결산후기준가: 증감                        0.0
통화                                NaN
Name: 2021-07-29, dtype: object

In [6]:
cols_num = ['기준가', '과표기준가', '수정기준가: 증감', 'KOSPI', '순자산총액', '설정잔액']
cols_num

['기준가', '과표기준가', '수정기준가: 증감', 'KOSPI', '순자산총액', '설정잔액']

In [5]:
preprocess_column_menu2160(df)

['펀드명',
 '펀드',
 '기준가',
 '기준가: 증감',
 '과표기준가',
 '과표기준가: 증감',
 '수정기준가',
 '수정기준가: 증감',
 'KOSPI',
 '수익률: 펀드',
 '수익률: KOSPI',
 '수익률: 초과',
 '순자산총액',
 '설정잔액',
 '편입비중: 주식',
 '편입비중: 채권',
 '편입비중: 파생',
 '편입비중: 단기',
 '펀드듀레이션',
 '결산여부',
 '결산후기준가',
 '결산후기준가: 증감',
 '통화']

In [7]:
df.columns = preprocess_column_menu2160(df)
df = df[pd.notna(df.index)]
df

,펀드명,펀드,기준가,기준가: 증감,과표기준가,과표기준가: 증감,수정기준가,수정기준가: 증감,KOSPI,수익률: 펀드: 펀드,...,설정잔액,편입비중: 주식: 주식,편입비중: 채권: 채권,편입비중: 파생: 파생,편입비중: 단기: 단기,펀드듀레이션,결산여부,결산후기준가,결산후기준가: 증감,통화
일자,,,,,,,,,,,,,,,,,,,,,
2025-02-13,라이프IPO일반사모투자신탁제2호,000005,"1,014.15",0.94,"1,007.69",0.05,"1,667.24",1.55,"2,583.17",0.09,...,"3,084,553,331.00",1.25,0,0,33.75,0.0,NaN,NaN,0.0,NaN
2025-02-13,라이프IPO일반사모투자신탁제2호 Class C,000006,"1,006.64",0.89,"1,000.20",0.01,"1,530.33",1.35,"2,583.17",0.09,...,"3,096,852,301.00",0,0,0,0,0.0,NaN,NaN,0.0,NaN
2025-02-13,라이프IPO전문투자형사모투자신탁제3호,000012,999.87,0.30,"1,000.75",0.07,"1,380.03",0.41,"2,583.17",0.03,...,"700,133,108.00",0.90,0,0,98.94,0.0,NaN,NaN,0.0,NaN
2025-02-13,라이프IPO전문투자형사모투자신탁제3호 Class C,000014,999.30,0.24,"1,000.18",0.01,"1,279.96",0.31,"2,583.17",0.02,...,"700,133,029.00",0,0,0,0,0.0,NaN,NaN,0.0,NaN
2025-02-13,라이프SPAC일반사모투자신탁제1호,000018,997.70,0.74,"1,012.33",0.03,"1,524.22",1.13,"2,583.17",0.07,...,"6,388,142,854.00",70.05,0,0,34.03,0.0,NaN,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-02-13,한국증권금융 일임,A00011,"1,043.38",-0.06,"1,041.38",-0.16,"1,043.38",-0.06,"2,583.17",-0.01,...,"30,987,717,614.00",0.04,0,0,0,0.0,NaN,NaN,0.0,NaN
2025-02-13,라이프 주식 SJ 제3호,A00012,"1,072.72",3.78,"1,010.76",0.00,"1,072.72",3.78,"2,583.17",0.35,...,"10,000,000,000.00",91.30,0,0,8.55,0.0,NaN,NaN,0.0,NaN
2025-02-13,라이프 ESG형 7호,A00013,"1,051.87",2.77,"1,005.28",0.71,"1,051.87",2.77,"2,583.17",0.26,...,"10,000,000,000.00",84.86,0,0,16.11,0.0,NaN,NaN,0.0,NaN
2025-02-13,라이프 ESG형 8호,A00014,"1,037.57",2.75,"1,033.44",0.43,"1,037.57",2.75,"2,583.17",0.27,...,"10,000,000,000.00",85.37,0,0,14.77,0.0,NaN,NaN,0.0,NaN
2025-02-13,TMF(라이프사회책임1호),A00015,"1,053.95",5.75,"1,000.52",0.00,"1,053.95",5.75,"2,583.17",0.55,...,"20,000,000,000.00",92.34,0,0,10.36,0.0,NaN,NaN,0.0,NaN

In [33]:
import pandas as pd

df = load_menu2160_snapshot(date_ref='2025-02-13')

def get_df_preprocessed_column_menu2160(menu2160):
    col1 = menu2160.columns
    col2 = list(menu2160.iloc[0])
    data = {'col1':col1, 'col2':col2}
    df = pd.DataFrame(data)
    df['col1'] = df['col1'].apply(lambda x: x.replace('\n','').split('.')[0])
    df['col1'] = df['col1'].apply(lambda x: None if 'Unnamed:' in x else x)
    df['col2'] = df.apply(lambda x: x['col1'] if x['col1']=='증감' else x['col2'], axis=1)
    df['col2'] = df['col2'].apply(lambda x: '' if pd.isna(x) else x)
    df['col1'] = df['col1'].apply(lambda x: None if x=='증감' in x else x).ffill()
    df['col'] = df.apply(lambda x: f"{x['col1']}: {x['col2']}" if x['col2']!='' else x['col1'], axis=1)
    return df

def preprocess_column_menu2160(menu2160):
    df = get_df_preprocessed_column_menu2160(menu2160)
    col = list(df['col'])
    return col

1 Files matching the regex 'menu2160-code000000-at20250213' in the bucket 'dataset-system' with prefix 'dataset-menu2160-snapshot/':
Successfully read file: dataset-menu2160-snapshot/menu2160-code000000-at20250213-save20250214.csv
DataFrame shape: (175, 23)

In [34]:
df = load_menu2160_snapshot(date_ref='2025-02-13')
preprocess_column_menu2160(df)

1 Files matching the regex 'menu2160-code000000-at20250213' in the bucket 'dataset-system' with prefix 'dataset-menu2160-snapshot/':
Successfully read file: dataset-menu2160-snapshot/menu2160-code000000-at20250213-save20250214.csv
DataFrame shape: (175, 23)

['펀드명',
 '펀드',
 '기준가',
 '기준가: 증감',
 '과표기준가',
 '과표기준가: 증감',
 '수정기준가',
 '수정기준가: 증감',
 'KOSPI',
 '수익률: 펀드',
 '수익률: KOSPI',
 '수익률: 초과',
 '순자산총액',
 '설정잔액',
 '편입비중: 주식',
 '편입비중: 채권',
 '편입비중: 파생',
 '편입비중: 단기',
 '펀드듀레이션',
 '결산여부',
 '결산후기준가',
 '결산후기준가: 증감',
 '통화']

In [5]:
preprocess_timeseries_menu2160(df)

              price
date
2025-02-12  1000.00
2025-02-13  1179.42
2025-02-13  1157.52
2025-02-13  1376.49
2025-02-13  1120.73
...             ...
2025-02-13  1757.84
2025-02-13  1668.98
2025-02-13  1663.22
2025-02-13  1004.59
2025-02-13  1616.90

[175 rows x 1 columns]