In [1]:
from financial_dataset_preprocessor import *

INFO:shining_pebbles:shining_pebbles package initialized
INFO:aws_s3_controller:aws_s3_controller package initialized
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials

In [2]:
from financial_dataset_loader import *

In [3]:
df = load_menu2160_snapshot(date_ref='2025-02-13')
df

1 Files matching the regex 'menu2160-code000000-at20250213' in the bucket 'dataset-system' with prefix 'dataset-menu2160-snapshot/':
Successfully read file: dataset-menu2160-snapshot/menu2160-code000000-at20250213-save20250214.csv
DataFrame shape: (175, 23)

,펀드명,펀드,기준가,증감,과표\n기준가,증감.1,수정\n기준가,증감.2,KOSPI,수익률,...,설정잔액,편입비중,Unnamed: 16,Unnamed: 17,Unnamed: 18,펀드\n듀레이션,결산\n여부,결산후\n기준가,증감.3,통화
일자,,,,,,,,,,,,,,,,,,,,,
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,펀드,...,NaN,주식,채권,파생,단기,NaN,NaN,NaN,NaN,NaN
2025-02-13,라이프IPO일반사모투자신탁제2호,000005,"1,014.15",0.94,"1,007.69",0.05,"1,667.24",1.55,"2,583.17",0.09,...,"3,084,553,331.00",1.25,0,0,33.75,0.0,NaN,NaN,0.0,NaN
2025-02-13,라이프IPO일반사모투자신탁제2호 Class C,000006,"1,006.64",0.89,"1,000.20",0.01,"1,530.33",1.35,"2,583.17",0.09,...,"3,096,852,301.00",0,0,0,0,0.0,NaN,NaN,0.0,NaN
2025-02-13,라이프IPO전문투자형사모투자신탁제3호,000012,999.87,0.30,"1,000.75",0.07,"1,380.03",0.41,"2,583.17",0.03,...,"700,133,108.00",0.90,0,0,98.94,0.0,NaN,NaN,0.0,NaN
2025-02-13,라이프IPO전문투자형사모투자신탁제3호 Class C,000014,999.30,0.24,"1,000.18",0.01,"1,279.96",0.31,"2,583.17",0.02,...,"700,133,029.00",0,0,0,0,0.0,NaN,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-02-13,한국증권금융 일임,A00011,"1,043.38",-0.06,"1,041.38",-0.16,"1,043.38",-0.06,"2,583.17",-0.01,...,"30,987,717,614.00",0.04,0,0,0,0.0,NaN,NaN,0.0,NaN
2025-02-13,라이프 주식 SJ 제3호,A00012,"1,072.72",3.78,"1,010.76",0.00,"1,072.72",3.78,"2,583.17",0.35,...,"10,000,000,000.00",91.30,0,0,8.55,0.0,NaN,NaN,0.0,NaN
2025-02-13,라이프 ESG형 7호,A00013,"1,051.87",2.77,"1,005.28",0.71,"1,051.87",2.77,"2,583.17",0.26,...,"10,000,000,000.00",84.86,0,0,16.11,0.0,NaN,NaN,0.0,NaN
2025-02-13,라이프 ESG형 8호,A00014,"1,037.57",2.75,"1,033.44",0.43,"1,037.57",2.75,"2,583.17",0.27,...,"10,000,000,000.00",85.37,0,0,14.77,0.0,NaN,NaN,0.0,NaN
2025-02-13,TMF(라이프사회책임1호),A00015,"1,053.95",5.75,"1,000.52",0.00,"1,053.95",5.75,"2,583.17",0.55,...,"20,000,000,000.00",92.34,0,0,10.36,0.0,NaN,NaN,0.0,NaN

In [4]:
preprocess_menu2160(df)

,펀드명,펀드,기준가,기준가: 증감,과표기준가,과표기준가: 증감,수정기준가,수정기준가: 증감,KOSPI,수익률: 펀드,...,설정잔액,편입비중: 주식,편입비중: 채권,편입비중: 파생,편입비중: 단기,펀드듀레이션,결산여부,결산후기준가,결산후기준가: 증감,통화
일자,,,,,,,,,,,,,,,,,,,,,
2025-02-13,라이프IPO일반사모투자신탁제2호,000005,1014.15,0.94,1007.69,0.05,"1,667.24",1.55,2583.17,0.09,...,3.084553e+09,1.25,0,0,33.75,0.0,NaN,NaN,0.0,NaN
2025-02-13,라이프IPO일반사모투자신탁제2호 Class C,000006,1006.64,0.89,1000.20,0.01,"1,530.33",1.35,2583.17,0.09,...,3.096852e+09,0,0,0,0,0.0,NaN,NaN,0.0,NaN
2025-02-13,라이프IPO전문투자형사모투자신탁제3호,000012,999.87,0.30,1000.75,0.07,"1,380.03",0.41,2583.17,0.03,...,7.001331e+08,0.90,0,0,98.94,0.0,NaN,NaN,0.0,NaN
2025-02-13,라이프IPO전문투자형사모투자신탁제3호 Class C,000014,999.30,0.24,1000.18,0.01,"1,279.96",0.31,2583.17,0.02,...,7.001330e+08,0,0,0,0,0.0,NaN,NaN,0.0,NaN
2025-02-13,라이프SPAC일반사모투자신탁제1호,000018,997.70,0.74,1012.33,0.03,"1,524.22",1.13,2583.17,0.07,...,6.388143e+09,70.05,0,0,34.03,0.0,NaN,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-02-13,한국증권금융 일임,A00011,1043.38,-0.06,1041.38,-0.16,"1,043.38",-0.06,2583.17,-0.01,...,3.098772e+10,0.04,0,0,0,0.0,NaN,NaN,0.0,NaN
2025-02-13,라이프 주식 SJ 제3호,A00012,1072.72,3.78,1010.76,0.00,"1,072.72",3.78,2583.17,0.35,...,1.000000e+10,91.30,0,0,8.55,0.0,NaN,NaN,0.0,NaN
2025-02-13,라이프 ESG형 7호,A00013,1051.87,2.77,1005.28,0.71,"1,051.87",2.77,2583.17,0.26,...,1.000000e+10,84.86,0,0,16.11,0.0,NaN,NaN,0.0,NaN
2025-02-13,라이프 ESG형 8호,A00014,1037.57,2.75,1033.44,0.43,"1,037.57",2.75,2583.17,0.27,...,1.000000e+10,85.37,0,0,14.77,0.0,NaN,NaN,0.0,NaN
2025-02-13,TMF(라이프사회책임1호),A00015,1053.95,5.75,1000.52,0.00,"1,053.95",5.75,2583.17,0.55,...,2.000000e+10,92.34,0,0,10.36,0.0,NaN,NaN,0.0,NaN

In [5]:
preprocess_timeseries_menu2160(df)

              price
date
2025-02-12  1000.00
2025-02-13  1179.42
2025-02-13  1157.52
2025-02-13  1376.49
2025-02-13  1120.73
...             ...
2025-02-13  1757.84
2025-02-13  1668.98
2025-02-13  1663.22
2025-02-13  1004.59
2025-02-13  1616.90

[175 rows x 1 columns]